name: NumberWorkflow
on:
  workflow_dispatch:
    inputs:
      get_number_from_user:
        description: 'Enter a number'
        required: true
        type: number
        default: '0'

jobs:
  the-standard-job:
    runs-on: ubuntu-latest
    env:
      INPUT_NUMBER_FROM_USER: ${{ inputs.get_number_from_user }}
    steps:
      - name: number > 7 as input
        if: inputs.get_number_from_user > 7
        run: echo "input was greater than 7 ${{ secrets.MY_REAL_NAME }}"

      - name: number less than 7 as input
        run: echo "input was lower than 7 :("
        if: inputs.get_number_from_user < 7

      - name: testing env veriable
        run: echo "The env var is set to $INPUT_NUMBER_FROM_USER witch is set to ${{ inputs.get_number_from_user }}"

      - name: bash Script
        shell: bash
        run: |
          echo "Hello, i may fail by reading the env var $MY_MAPPED_ENV_VAR wich is set to ${{ inputs.get_number_from_user }}"
          if [ 2 = $MY_MAPED_ENV_VAR ]; then
            exit 42
          fi
        env:
          MY_MAPPED_ENV_VAR: ${{ inputs.get_number_from_user }}
        
